"""
VisionGuard Shared Core Data Models.
Provides strongly typed Pydantic models for frames, detections, tracks, events,
regions, and system performance metrics exchanged between pipeline components.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple
import uuid
import numpy as np
from pydantic import BaseModel, Field, ConfigDict


class TrackState(str, Enum):
    NEW = "new"
    TRACKED = "tracked"
    LOST = "lost"
    REMOVED = "removed"


class CameraState(str, Enum):
    DISCONNECTED = "disconnected"
    CONNECTING = "connecting"
    STREAMING = "streaming"
    PAUSED = "paused"
    ERROR = "error"
    STOPPED = "stopped"


class SeverityLevel(str, Enum):
    INFO = "info"
    WARNING = "warning"
    ALERT = "alert"
    CRITICAL = "critical"


class RegionType(str, Enum):
    POLYGON = "polygon"
    LINE = "line"
    ROI = "roi"


class FrameData(BaseModel):
    """Encapsulates frame image data and acquisition metadata."""
    model_config = ConfigDict(arbitrary_types_allowed=True)

    frame_id: int
    camera_id: str
    timestamp: float = Field(default_factory=lambda: datetime.now().timestamp())
    image: np.ndarray  # Raw BGR frame matrix
    annotated_image: Optional[np.ndarray] = None
    width: int
    height: int
    fps: float = 0.0

    def copy_metadata(self) -> Dict[str, Any]:
        return {
            "frame_id": self.frame_id,
            "camera_id": self.camera_id,
            "timestamp": self.timestamp,
            "width": self.width,
            "height": self.height,
        }


class Detection(BaseModel):
    """Bounding box detection produced by an Inference Engine."""
    bbox: Tuple[float, float, float, float]  # (x1, y1, x2, y2)
    confidence: float
    class_id: int
    class_name: str

    @property
    def x1(self) -> float: return self.bbox[0]
    @property
    def y1(self) -> float: return self.bbox[1]
    @property
    def x2(self) -> float: return self.bbox[2]
    @property
    def y2(self) -> float: return self.bbox[3]

    @property
    def width(self) -> float: return self.x2 - self.x1
    @property
    def height(self) -> float: return self.y2 - self.y1

    @property
    def centroid(self) -> Tuple[float, float]:
        return ((self.x1 + self.x2) / 2.0, (self.y1 + self.y2) / 2.0)


class Track(BaseModel):
    """Tracked object state maintained by the Multi-Object Tracker."""
    track_id: int
    class_id: int
    class_name: str
    confidence: float
    bbox: Tuple[float, float, float, float]  # (x1, y1, x2, y2)
    centroid: Tuple[float, float]
    trajectory: List[Tuple[float, float]] = Field(default_factory=list)
    velocity: Tuple[float, float] = (0.0, 0.0)
    state: TrackState = TrackState.TRACKED
    age: int = 1
    time_since_update: int = 0
    stationary_duration_sec: float = 0.0
    first_seen_timestamp: float = Field(default_factory=lambda: datetime.now().timestamp())
    last_seen_timestamp: float = Field(default_factory=lambda: datetime.now().timestamp())

    @property
    def x1(self) -> float: return self.bbox[0]
    @property
    def y1(self) -> float: return self.bbox[1]
    @property
    def x2(self) -> float: return self.bbox[2]
    @property
    def y2(self) -> float: return self.bbox[3]


class Region(BaseModel):
    """Geometrical detection zone, counting line, or ROI mask."""
    id: str
    name: str
    region_type: RegionType
    points: List[Tuple[float, float]]
    direction: Optional[str] = "bidirectional"  # left_to_right, right_to_left, bidirectional
    color: Tuple[int, int, int] = (0, 255, 0)
    enabled: bool = True


class Event(BaseModel):
    """Intelligent scene event generated by Event Engine plugins."""
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = Field(default_factory=lambda: datetime.now().timestamp())
    camera_id: str
    event_type: str
    severity: SeverityLevel = SeverityLevel.WARNING
    object_id: Optional[int] = None
    object_class: Optional[str] = None
    confidence: float = 1.0
    zone_id: Optional[str] = None
    zone_name: Optional[str] = None
    snapshot_path: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class PerformanceMetrics(BaseModel):
    """Real-time system telemetry and performance parameters."""
    timestamp: float = Field(default_factory=lambda: datetime.now().timestamp())
    fps: float = 0.0
    frame_processing_latency_ms: float = 0.0
    detection_latency_ms: float = 0.0
    tracking_latency_ms: float = 0.0
    cpu_usage_pct: float = 0.0
    memory_mb: float = 0.0
    frame_drop_count: int = 0
